<a href="https://colab.research.google.com/github/kalyankuna124/OIBSIP/blob/main/iris_flower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Subbmited by kalyan Kuna**

### Importing Libraries

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading Dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data science/Iris.csv')

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
# Id column is not needed as it is not informative for the data training model 

df.drop('Id', axis=1, inplace=True)

In [ ]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

In [ ]:
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

### Train-Test Data Splitting

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=True)

In [ ]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
35             5.0           3.2            1.2           0.2
85             6.0           3.4            4.5           1.6
51             6.4           3.2            4.5           1.5
115            6.4           3.2            5.3           2.3
129            7.2           3.0            5.8           1.6
..             ...           ...            ...           ...
66             5.6           3.0            4.5           1.5
104            6.5           3.0            5.8           2.2
86             6.7           3.1            4.7           1.5
71             6.1           2.8            4.0           1.3
112            6.8           3.0            5.5           2.1

[120 rows x 4 columns]

In [ ]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
139            6.9           3.1            5.4           2.1
7              5.0           3.4            1.5           0.2
37             4.9           3.1            1.5           0.1
61             5.9           3.0            4.2           1.5
33             5.5           4.2            1.4           0.2
137            6.4           3.1            5.5           1.8
79             5.7           2.6            3.5           1.0
31             5.4           3.4            1.5           0.4
50             7.0           3.2            4.7           1.4
121            5.6           2.8            4.9           2.0
87             6.3           2.3            4.4           1.3
18             5.7           3.8            1.7           0.3
143            6.8           3.2            5.9           2.3
75             6.6           3.0            4.4           1.4
67             5.8           2.7            4.1           1.0
103            6.3           2.9            5.6           1.8
134            6.1           2.6            5.6           1.4
124            6.7           3.3            5.7           2.1
84             5.4           3.0            4.5           1.5
133            6.3           2.8            5.1           1.5
88             5.6           3.0            4.1           1.3
125            7.2           3.2            6.0           1.8
145            6.7           3.0            5.2           2.3
120            6.9           3.2            5.7           2.3
60             5.0           2.0            3.5           1.0
11             4.8           3.4            1.6           0.2
20             5.4           3.4            1.7           0.2
94             5.6           2.7            4.2           1.3
58             6.6           2.9            4.6           1.3
80             5.5           2.4            3.8           1.1

In [ ]:
y_train

35         Iris-setosa
85     Iris-versicolor
51     Iris-versicolor
115     Iris-virginica
129     Iris-virginica
            ...
66     Iris-versicolor
104     Iris-virginica
86     Iris-versicolor
71     Iris-versicolor
112     Iris-virginica
Name: Species, Length: 120, dtype: object

In [ ]:
y_test

139     Iris-virginica
7          Iris-setosa
37         Iris-setosa
61     Iris-versicolor
33         Iris-setosa
137     Iris-virginica
79     Iris-versicolor
31         Iris-setosa
50     Iris-versicolor
121     Iris-virginica
87     Iris-versicolor
18         Iris-setosa
143     Iris-virginica
75     Iris-versicolor
67     Iris-versicolor
103     Iris-virginica
134     Iris-virginica
124     Iris-virginica
84     Iris-versicolor
133     Iris-virginica
88     Iris-versicolor
125     Iris-virginica
145     Iris-virginica
120     Iris-virginica
60     Iris-versicolor
11         Iris-setosa
20         Iris-setosa
94     Iris-versicolor
58     Iris-versicolor
80     Iris-versicolor
Name: Species, dtype: object

### Model Building, Training and Evaluation

In [ ]:
# Training the model with Logistic Regression and checking the score/accuracy

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.9666666666666667

In [ ]:
# Training the model with K Nearest Neighbour Clssification and checking the score/accuracy

from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier(n_neighbors=10)

model_KNN.fit(X_train, y_train)

model_KNN.score(X_test, y_test)

1.0

### Model Predictions

In [ ]:
model.predict([[5.1, 3.8, 1.9, 0.4]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

In [ ]:
df.iloc[44]

SepalLengthCm            5.1
SepalWidthCm             3.8
PetalLengthCm            1.9
PetalWidthCm             0.4
Species          Iris-setosa
Name: 44, dtype: object